# Generated by Django 5.1.5 on 2025-01-17 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-creado_en"],
                "verbose_name": "Tarea",
                "verbose_name_plural": "Tareas",
            },
        ),
        migrations.AlterField(
            model_name="task",
            name="descripcion",
            field=models.TextField(
                blank=True, help_text="Descripción detallada de la tarea"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("in_progress", "En Progreso"),
                    ("completed", "Completada"),
                ],
                default="pending",
                help_text="Estado actual de la tarea",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="fecha_vencimiento",
            field=models.DateField(
                blank=True, help_text="Fecha límite para completar la tarea", null=True
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="titulo",
            field=models.CharField(help_text="Título de la tarea", max_length=200),
        ),
        migrations.AlterField(
            model_name="task",
            name="usuario",
            field=models.ForeignKey(
                help_text="Usuario propietario de la tarea",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tareas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
